apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: socket-app-gitops
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/aziz-mevlana/kubernetes-03-production-ready-RKE2-HA-cluster'
    path: deployments/socket-chart  # Doğru klasör yolu ve harf hatası düzeltilmiş hali
    targetRevision: HEAD
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: socket-app  # Sadece düz namespace adı (slash içermez)
  syncPolicy:
    automated:  
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true  # Eksik namespace'i otomatik oluşturur