apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istio-gateway
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://aziz-mevlana.github.io/kubernetes-03-production-ready-RKE2-HA-cluster/
    chart: gateway
    targetRevision: 1.30.4
    helm:
      parameters:
        - name: service.type
          value: NodePort
        - name: autoscaling.enabled
          value: "false"
      values: |
        service:
          ports:
            - name: status-port
              port: 15021
              protocol: TCP
              targetPort: 15021
            - name: http2
              port: 80
              protocol: TCP
              targetPort: 80
            - name: https
              port: 443
              protocol: TCP
              targetPort: 443
            - name: tcp-socket
              port: 31400
              protocol: TCP
              nodePort: 31400
  destination:
    server: https://kubernetes.default.svc
    namespace: istio-ingress
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true