apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: socket-app-gitops
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://aziz-mevlana.github.io/kubernetes-03-production-ready-RKE2-HA-cluster/'
    chart: socket-chart
    targetRevision: 1.1.0
    helm:
      parameters:
        - name: istio.enabled
          value: "true"
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: socket-app
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true