{{- if or (and .Values.django.secretKey (ne .Values.django.secretKey "")) (not (lookup "v1" "Secret" .Release.Namespace (include "django-chart.fullname" .))) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "django-chart.fullname" . }}
  labels:
    {{- include "django-chart.labels" . | nindent 4 }}
type: Opaque
data:
  DJANGO_SECRET_KEY: {{ (default (randAlphaNum 50) .Values.django.secretKey) | b64enc | quote }}
{{- end }}